name: Deploy to Staging
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Simulate deployment delay
        sleep 30
        echo "Deployment completed"
    
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        python -c "import requests; print('Health check passed')"
